# 1. ingreso de liquidación de sueldo
nom = input ("Ingrese nombre empleado: ")
rut = input ("Ingrese rut empleado: ")
horasTrabajadas = int(input ("Ingrese las horas trabajadas: "))
valorHora = int(input("Ingrese el valor hora del empleado: "))
colacion = int(5500)
movilizacion = int(3000)
resultado = (valorHora * horasTrabajadas)+colacion+movilizacion
print(f"-----LIQUIDACIÓN EMPLEADO----")
print(f"NOMBRE EMPLEADO: {nom}")
print(f"RUT EMPLEADO: {rut}")
print(f"MOVILIZACIÓN: {movilizacion}")
print(f"ALIMENTACIÓN: {colacion}")
print(f"PAGO A EMPLEADO: {resultado}")
# 2. 
print("Ingrese los siguientes datos:")
nombre = input("Las 2 primeras letras de su primer nombre: ")
apellido = input("Las 2 primeras letras de su segundo apellido: ")
rut = input("Los 2 primeros números de su rut: ")
mes = input("Las 3 letras iniciales del mes de su nacimiento: ")
ciudad = input("Las 2 últimas letras de la ciudad donde vive: ")
opcion1 = nombre + apellido + rut + mes + ciudad
opcion2 = nombre + rut + apellido + mes + ciudad + mes
opcion3 = rut + nombre + mes + ciudad + apellido
opcion4 = apellido + rut + nombre + mes + ciudad + rut
opcion5 = ciudad + apellido + nombre +rut + mes + ciudad
print("")
print(f"La opción 1 de contraseña es: {opcion1}")
print(f"La opción 2 de contraseña es: {opcion2}")
print(f"La opción 3 de contraseña es: {opcion3}")
print(f"La opción 4 de contraseña es: {opcion4}")
print(f"La opción 5 de contraseña es: {opcion5}")
# 3.
posicionA = "X"
posicionB = ""
posicionC = ""
posicionD = ""
posicionE = "X"
posicionF = ""
posicionG = ""
posicionH = ""
posicionI = "X"
print("")
print("\t\t|\t\t |\t")
print(f"\t{posicionA}\t|\t{posicionB}\t |\t{posicionC}")
print("\t\t|\t\t |\t")
print("----------------------------------------------------")
print("\t\t|\t\t |\t")
print(f"\t{posicionD}\t|\t{posicionE}\t |\t{posicionF}")
print("\t\t|\t\t |\t")
print("----------------------------------------------------")
print("\t\t|\t\t |\t")
print(f"\t{posicionG}\t|\t{posicionH}\t |\t{posicionI}")
print("\t\t|\t\t |\t")
print("")
# 4.
print("Ingresar los datos de la venta")
cliente = input("Ingrese el nombre del cliente: ")
precio1 = int(input("Ingrese el precio del producto1: "))
cantidad1 = int(input("Ingrese la cantidad del producto1: "))
precio2 = int(input("Ingrese el precio del producto2: "))
cantidad2 = int(input("Ingrese la cantidad del producto2: "))
precio3 = int(input("Ingrese el precio del producto3: "))
cantidad3 = int(input("Ingrese la cantidad del producto3: "))
descuento = int(input("Ingrese el decuento: "))
total_bruto = (precio1 * cantidad1) + (precio2 * cantidad2) + (precio2 *cantidad2)
precio_con_descuento = round(total_bruto - (total_bruto *descuento/100))
iva = round(precio_con_descuento * 0.19)
print("")
print(f"Cliente: \t{cliente}")
print(f"Total bruto: \t${total_bruto}")
print(f"Total desc.: \t${precio_con_descuento}")
print(f"Iva: \t\t${iva}")
print(f"Total: \t\t${precio_con_descuento + iva}")
# 5.
linea18 =(" [_,_]) \ / \|")
linea1 = (" ___ |\________/)")
linea15 =(" ||'-'/--. / /\\ =| \|\\ \\")
linea11 =(" /|=T=|] / __ __\\")
linea13 =(" |\ ' // |_ 9 p ]\\")
linea6 =(" | | _H__/ _| : |")
linea16 =(" /|| <\/> |\ | '._, @ @)<_)")
linea21 =(" | |\ | | \.__/(_;_)")
linea31 =(" | . H | | : '='|")
linea2 =(" .-' | | | | ':")
linea7 =(" \ '.__ \ / ; ';")
linea19 =(" __'-._(_}==.' : ;")
linea71 =(" (___| /-' | :. :")
linea371 =(" [.-' \ | \ \ ; :")
linea414 =("| .' '-. | \ /")
linea22 =(" / |==| \ \ / \_")
linea661 =(" / [ | '._\_ -._ \\")
linea517 =(" / \__) __.- \ \ )\\")
linea81 =("/ | /.' >>)")
linea61 =("| \ |\ |")
linea651 =("| / / / / /")
linea51 =(" | /")
linea41 =("")
print(linea1)
print(linea18)
print(linea11)
print(linea13)
print(linea15)
print(linea16)
print(linea21)
print(linea31)
print(linea6)
print(linea7)
print(linea19)
print(linea71)
print(linea371)
print(linea2)
print(linea22)
print(linea661)
print(linea517)
print(linea81)
print(linea61)
print(linea414)
print(linea651)
print(linea51)
print(linea41)
